apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: case-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: hakankocagoz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: case-service
            port:
              number: 80